### ISSUE TITLE
Name the exported .txc correctly

### ISSUE THREAD

**Issue by austin-garrard** [translation-cards/txc-maker#57]
Right now it is named {session id}/deck.json. It should be named according to the name input by the user.

**Comment by PatrickDale** [comment]
When downloading file to Android app, it is not recognizable as a file that can be opened by Translation Cards. This is because it is missing the .txc extension in the deck filename.

DriveService.txc
![image](https://cloud.githubusercontent.com/assets/5590812/18452150/693c6a44-78ff-11e6-9102-4cdf5d3335a1.png)
